import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import  Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import ClientReduxWrapper from "./redux/ClientReduxWrapper";
import { Toaster } from "react-hot-toast";
import { LanguageProvider } from "@/context/LanguageContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    > 
      <body className="min-h-full flex flex-col">
        <ClientReduxWrapper>
        <LanguageProvider>
        <Navbar/>
        {children}
        <Footer/>
        <Toaster />
        </LanguageProvider>
        </ClientReduxWrapper>
        </body>
    </html>
  );
}



